name: hooks_riverpod
description: >
  A simple way to access state from anywhere in your application
  while robust and testable.
version: 2.0.0-dev.9
homepage: https://riverpod.dev
repository: https://github.com/rrousselGit/riverpod

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_riverpod: 2.0.0-dev.9
  riverpod:
    git:
      url: https://github.com/rrousselGit/riverpod
      ref: 24d9f09ebcd36f07a0fb49920d1456ea75392659
      path: packages/riverpod

  state_notifier: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
